-- CREATE DATABASE wtd IF NOT EXISTS
CREATE TABLE  wtd (
  wtdId INT AUTO_INCREMENT NOT NULL,
  title VARCHAR(200) NOT NULL,
  comment VARCHAR(500) NOT NULL,
  tags VARCHAR(200) NOT NULL,
     PRIMARY KEY (wtdId)

);

CREATE TABLE tasks (
  taskId INT AUTO_INCREMENT NOT NULL,
  content VARCHAR(200) NOT NULL,
  position INT NOT NULL,
  wtdId INT NOT NULL,
   PRIMARY KEY (taskId),
  FOREIGN KEY (wtdId) REFERENCES wtd(wtdId)
);